### ISSUE TITLE
help install

### ISSUE THREAD

**Issue by xoceunder** [manjurulhoque/laravel-airbnb#1]
help install my hosting
@manjurulhoque

**Comment by manjurulhoque** [comment]
Are you trying to install it into your cPanel?

**Comment by xoceunder** [comment]
Yes

**Comment by raam221027** [comment]
Please help me with how to install it and what version it needs to install it, just for school purposes.

**Comment by matosagencia** [comment]
i try install in xampp i get this error:

Fatal error: Uncaught RuntimeException: A facade root has not been set. in C:\xampp\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php:350 Stack trace: #0 C:\xampp\vendor\laravel\framework\src\Illuminate\Foundation\Exceptions\RegisterErrorViewPaths.php(16): Illuminate\Support\Facades\Facade::__callStatic('replaceNamespac...', Array) #1 C:\xampp\vendor\laravel\framework\src\Illuminate\Foundation\Exceptions\Handler.php(659): Illuminate\Foundation\Exceptions\RegisterErrorViewPaths->__invoke() #2 C:\xampp\vendor\laravel\framework\src\Illuminate\Foundation\Exceptions\Handler.php(640): Illuminate\Foundation\Exceptions\Handler->registerErrorViewPaths() #3 C:\xampp\vendor\laravel\framework\src\Illuminate\Foundation\Exceptions\Handler.php(571): Illuminate\Foundation\Exceptions\Handler->renderHttpException(Object(Symfony\Component\HttpKernel\Exception\HttpException)) #4 C:\xampp\vendor\laravel\framework\src\Illuminate\Foundation\Exceptions\Handler.php(477): Illuminate\Foundation\Exceptions\Handler->prepareResponse(Object(Illuminate\Http\Request), Object(Symfony\Component\HttpKernel\Exception\HttpException)) #5 C:\xampp\vendor\laravel\framework\src\Illuminate\Foundation\Exceptions\Handler.php(394): Illuminate\Foundation\Exceptions\Handler->renderExceptionResponse(Object(Illuminate\Http\Request), Object(Error)) #6 C:\xampp\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(503): Illuminate\Foundation\Exceptions\Handler->render(Object(Illuminate\Http\Request), Object(Error)) #7 C:\xampp\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(148): Illuminate\Foundation\Http\Kernel->renderException(Object(Illuminate\Http\Request), Object(Error)) #8 C:\xampp\htdocs\laravel-airbnb-master\public\index.php(54): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request)) #9 C:\xampp\htdocs\laravel-airbnb-master\server.php(21): require_once('C:\\xampp\\htdocs...') #10 {main} thrown in C:\xampp\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php on line 350
